# Generated by Django 4.0.1 on 2022-10-17 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='fullname')),
                ('rfid', models.CharField(blank=True, max_length=255, null=True, verbose_name='rfid')),
                ('date_appointment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_appointment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
