# Generated by Django 4.0.1 on 2022-11-27 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0.0, verbose_name='user_id')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_in')),
                ('time_out', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_out')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
