# Generated by Django 4.0.1 on 2022-11-27 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logs_time_type_alter_logs_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='time_out',
        ),
        migrations.AddField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
