# Generated by Django 4.0.1 on 2022-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='office_name')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
